### ISSUE TITLE
cant work with neither nick sites on nick_eu.py

### ISSUE THREAD

**Issue by itzikvil** [turicfr/nick-downloader#4]
Hi,

i love what you did with that script though I cant seem to work with that script on Israel site and almost any other site i choose for tests cant download...
i installed everything as requested, all predefined and still get errors, when i open nick_eu.py i get list of countries, i choose 28 (israel) and i get out put which series (i am not getting a list of programs/series) and whatever number i choose i get error:
Which language? 28
Which series? 2
Traceback (most recent call last):
  File "C:\Users\itzikv\Desktop\nick-downloader-master\nick_eu.py", line 121, in <module>
    main()
  File "C:\Users\itzikv\Desktop\nick-downloader-master\nick_eu.py", line 116, in main
    series = choose(Series.get_series(region["lang"], region["locale"]), "series")
  File "C:\Users\itzikv\Desktop\nick-downloader-master\nick_eu.py", line 110, in choose
    return items[int(input(f"Which {name}? ")) - 1]
IndexError: list index out of range

hoe you can help with this, and you are doing great work i love the option to download directly and with high resolution, 
hope you can assist 👍 

thanks,

Itzik

**Comment by turicfr** [comment]
Hey, thanks for filling an issue!

Currently, `nick_eu.py` only works for a couple of countries in Europe. Nickelodeon Israel (among many other countries) uses a different API from other countries in Europe. Thus, this script cannot be used to download from Israel.

Support for specific countries might be implemented in the future.

**Comment by itzikvil** [comment]
Hi,

thanks for getting back to me and so fast :) is there any chance you can expedite or customize the current nick.py to connect to Israel Nickelodeon API so I will be able to connect and DL data from there? no nick_eu.py only nick.py for 1 site as you already did for U.S.

thanks you very much for what your doing,

itzik

**Comment by turicfr** [comment]
Since Nickelodeon Israel uses a website to host their videos (unlike other countries which allow to watch videos only on a mobile application), I prefer to simply add support for it in [`youtube-dl`](https://github.com/ytdl-org/youtube-dl).

I've just [tossed a PR](https://github.com/ytdl-org/youtube-dl/pull/27417) that adds support for Nickelodeon Israel.
